#!/usr/bin/env bash
set -u
printf 'mpirun' >>"${QBOX_MOCK_COMMAND_LOG:?}"
printf ' <%s>' "$@" >>"$QBOX_MOCK_COMMAND_LOG"
printf '\n' >>"$QBOX_MOCK_COMMAND_LOG"
if [ "${1-}" = -np ]; then shift 2; fi
exec "$@"
