"""Install an optional user command bound to this Python environment.

Run once after installing qbox: python -m qbox.install
This does not install dependencies, activate environments or edit shell profiles.
"""
import argparse
import os
from pathlib import Path
import shlex
import sys
import tempfile


def install_command(bin_dir):
    # Do not resolve symlinks: venv/bin/python must retain its environment identity.
    python = os.path.abspath(sys.executable)
    content = (
        '#!/bin/sh\n'
        '# qbox user command; generated by python -m qbox.install\n'
        f'QBOX_PYTHON={shlex.quote(python)}\n'
        'export QBOX_PYTHON\n'
        'if [ ! -x "$QBOX_PYTHON" ]; then\n'
        '    printf "%s\\n" "qbox: Python environment is unavailable: $QBOX_PYTHON. '
        'Restore it or reinstall the qbox user command." >&2\n'
        '    exit 127\n'
        'fi\n'
        'exec "$QBOX_PYTHON" -m qbox "$@"\n'
    )
    directory = Path(bin_dir).expanduser().absolute()
    directory.mkdir(parents=True, exist_ok=True)
    target = directory / 'qbox'
    if target.is_symlink() or target.exists():
        if (not target.is_symlink() and target.is_file()
                and target.read_text(encoding='utf-8', errors='replace') == content
                and os.access(target, os.X_OK)):
            return target
        raise FileExistsError(f'{target} already exists; keep it or choose another --bin-dir. '
                              'Inspect and remove an obsolete command yourself before retrying.')
    # Publish an executable complete file without ever replacing an existing name.
    fd, temporary = tempfile.mkstemp(prefix='.qbox-command-', dir=directory)
    try:
        with os.fdopen(fd, 'w', encoding='utf-8') as stream:
            stream.write(content)
            stream.flush()
            os.fchmod(stream.fileno(), 0o755)
        os.link(temporary, target)
    finally:
        os.unlink(temporary)
    return target


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--bin-dir', default=str(Path.home() / '.local/bin'),
                        help='command directory (default: ~/.local/bin)')
    args = parser.parse_args(argv)
    if os.environ.get('_QBOX_OFFLINE_ROOT'):
        parser.exit(1, 'qbox: the complete offline installation already provides its own command.\n')
    try:
        target = install_command(args.bin_dir)
    except OSError as error:
        parser.exit(1, f'qbox: cannot install command: {error}\n')
    print(f'qbox command: {target}\nPython environment: {sys.executable}')
    print('No Python activation is needed when using this command.')
    print(f'For this shell: export PATH={shlex.quote(str(target.parent))}:"$PATH"')
    print('Add that PATH setting once to your shell profile if needed; profiles were not modified.')
    print('Check command selection with: command -v qbox')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
